version: 2

builds:
  - id: create_loads
    main: ./src/cmd/create_loads/main.go
    binary: bootstrap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: view_loads
    main: ./src/cmd/view_loads/main.go
    binary: bootstrap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: create_loads
    builds:
      - create_loads
    format: zip
    name_template: "drumkit-create-loads-{{ .Arch }}"
  - id: view_loads
    builds:
      - view_loads
    format: zip
    name_template: "drumkit-view-loads-{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:" 